{% set name = "marcel" %}
{% set version = "0.32.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geophile/marcel/archive/v{{ version }}.tar.gz
  sha256: e506b6f79acd60481996fede84cc45a1185e85adc322184e3535fac7397313e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - dill
    - setuptools
  run:
    - python >={{ python_min }}
    - dill
    - psutil
    - prompt_toolkit

test:
  imports:
    - marcel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.marceltheshell.org
  summary: A model shell that passes Python values; lists, tuples, strings, and numbers; but also objects representing files and processes.
  dev_url: https://github.com/geophile/marcel
  license: GPL-3.0-only
  license_file:
    - COPYING
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
