{% set name = "marcel" %}
{% set version = "0.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geophile/marcel/archive/v{{ version }}.tar.gz
  sha256: b51263c82d141d20c93c53eb5bc3051c7af6e48c0f5ff2ee29e467007b9c179a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dill
    - psutil

test:
  imports:
    - marcel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.marceltheshell.org
  summary: A model shell that passes Python values; lists, tuples, strings, and numbers; but also objects representing files and processes.
  dev_url: https://github.com/geophile/marcel
  license: GPL-3.0-only
  license_file:
    - COPYING
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
