{% set name = "marcel" %}
{% set version = "0.27.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geophile/marcel/archive/v{{ version }}.tar.gz
  sha256: 5396451435cbe6c5d977bedddee480c3dc6207562524786fccbf1f33b97bf78e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - dill
  run:
    - python >=3.9
    - dill
    - psutil

test:
  imports:
    - marcel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.marceltheshell.org
  summary: A model shell that passes Python values; lists, tuples, strings, and numbers; but also objects representing files and processes.
  dev_url: https://github.com/geophile/marcel
  license: GPL-3.0-only
  license_file:
    - COPYING
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
