{% set name = "marcel" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geophile/marcel/archive/v{{ version }}.tar.gz
  sha256: 174881ec03de7c9ee4a5da26b9df21f8a799da4153453ecdb0312796659e87bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dill
    - psutil

test:
  imports:
    - marcel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.marceltheshell.org
  summary: A model shell that passes Python values; lists, tuples, strings, and numbers; but also objects representing files and processes.
  dev_url: https://github.com/geophile/marcel
  license: GPL-3.0-only
  license_file:
    - COPYING
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
