schema_version: 1

context:
  name: marcel
  version: "0.36.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/geophile/marcel/archive/v${{ version }}.tar.gz
  sha256: 23a155a3c980cd8a66b3050d7919beaebe9505bfd0c03c7fda2816db997cd4d8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - dill
    - setuptools
  run:
    - python >=${{ python_min }}
    - dill
    - psutil
    - prompt_toolkit

tests:
  - python:
      imports:
        - marcel
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A model shell that passes Python values; lists, tuples, strings, and numbers; but also objects representing files and processes.
  license: GPL-3.0-only
  license_file:
    - COPYING
    - LICENSE
  homepage: https://www.marceltheshell.org
  repository: https://github.com/geophile/marcel

extra:
  recipe-maintainers:
    - thewchan
